config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "flats#index"
  get "flats/search", to: "flats#search"
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :find_flat, only: [:show]

  def index
    @flats = Flat.all
  end

  def show
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flat_path(@flat)
    else
      render :new
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def search
    @queryname = params[:search][:name]
    @total = Flat.all.count
    @flats = Flat.where("name LIKE '%#{params[:search][:name]}%'")
  end

  private

  def find_flat
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/edit.html.erb
<h1>Flats#edit</h1>
<p>Find me in app/views/flats/edit.html.erb</p>

app/views/flats/index.html.erb
<div class="container">
<div class="row row-cols-1 row-cols-md-3 my-3">
<% @flats.each do |flat| %>
  <div class="col mb-4 card-group">
    <div class="flat card">
      <img src="https://source.unsplash.com/random/?castle" class="card-img-top img-fluid">
      <div class="card-body">
        <h5 class="card-title"><%= flat.name %></h5>
        <p class="card-text"><%= flat.address %></p>
        <p class="card-text">
        <i class="fas fa-users pr-2"></i><%= flat.number_of_guests %>
        <i class="fas fa-dollar-sign pl-4 pr-2"></i><%= flat.price_per_night %>
        </p>
      </div>
      <div class="card-footer bg-transparent">
        <%= link_to "More Info", flat_path(flat), class: "text-primary text-left"  %>
        <%= link_to "Edit Flat", flat_path(flat), class: "text-warning text-center"  %>
        <%= link_to "Delete Flat", flat_path(flat), class: "text-danger text-right"  %>
      </div>
    </div>
  </div>
<% end %>
</div>
</div>

app/views/flats/new.html.erb
<div class="container">
<h1>Add a New Flat</h1>
<%= simple_form_for(@flat) do |f| %>
  <%= f.input :name  %>
  <%= f.input :address  %>
  <%= f.input :description, as: :text  %>
  <%= f.input :price_per_night, as: :integer  %>
  <%= f.input :number_of_guests, as: :integer  %>
  <%= f.submit "Create Flat", class: "btn btn-primary"  %><%= link_to "Cancel", new_flat_path, class: "btn btn-danger mx-2"  %>
<% end %>
</div>

app/views/flats/search.html.erb
<div class="container">
    <h1>Your Search Result</h1>
    <p>You searched for <b><%= @queryname %></b>, We found <%= @flats.count %> flats out of <%= @total %> on our website.</p>
<div class="row row-cols-1 row-cols-md-3 my-3">
<% @flats.each do |flat| %>
  <div class="col mb-4 card-group">
    <div class="flat card">
      <img src="https://source.unsplash.com/random/?castle" class="card-img-top img-fluid">
      <div class="card-body">
        <h5 class="card-title"><%= flat.name %></h5>
        <p class="card-text"><%= flat.address %></p>
        <p class="card-text">
        <i class="fas fa-users pr-2"></i><%= flat.number_of_guests %>
        <i class="fas fa-dollar-sign pl-4 pr-2"></i><%= flat.price_per_night %>
        </p>
      </div>
      <div class="card-footer bg-transparent">
        <%= link_to "More Info", flat_path(flat), class: "text-primary text-left"  %>
        <%= link_to "Edit Flat", flat_path(flat), class: "text-warning text-center"  %>
        <%= link_to "Delete Flat", flat_path(flat), class: "text-danger text-right"  %>
      </div>
    </div>
  </div>
<% end %>
</div>
</div>

app/views/flats/show.html.erb
<div style="background-image: url('https://source.unsplash.com/random/?castle')" class="hero"></div>

<div class="container mt-n5">
  <div class="row">
    <div class="col-8">
      <div class="card mb-2">
        <div class="card-body">
          <h5 class="card-title"><%= @flat.name %></h5>
          <p class="card-text"><%= @flat.address %></p>
        </div>
      </div>
      <div class="card mb-2">
        <div class="card-body">
          <h5 class="card-title">More about this flat</h5>
          <p class="card-text"><%= @flat.description %></p>
        </div>
      </div>
    </div>
    <div class="col-4">
      <div class="card mb-2">
        <div class="card-body">
          <h5 class="card-title">Book this shit man!</h5>
          <%= link_to "Button", root_path  %>
        </div>
      </div>
      <div class="card mb-2">
        <div class="card-body">
          <h5 class="card-title">Details</h5>
          <p class="card-text">
            <i class="fas fa-users pr-2"></i><%= @flat.number_of_guests %>
            <i class="fas fa-dollar-sign pl-4 pr-2"></i><%= @flat.price_per_night %>
          </p>
        </div>
      </div>
      <div class="card mb-2">
        <div class="card-body">
          <h5 class="card-title">Share this shit yo</h5>
          <p class="card-text">
            <i class="fab fa-twitter"></i>
            <i class="fab fa-facebook"></i>
            <i class="fab fa-instagram"></i>
            <i class="fab fa-youtube"></i>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-light bg-light">
  <%= link_to "Simple Airbnb", root_path, class: "navbar-brand"  %>
  <%= simple_form_for(:search, url: flats_search_path, method: "GET", html: { class: "form-inline"}) do |f| %>
    <%= f.input :name, label: false, class: "form-control mr-sm-2" %>
    <%= f.submit "Search", class: "btn btn-outline-success my-2 my-sm-0 mx-1" %>
    <%= link_to "Add Flat", new_flat_path, class: "btn btn-outline-primary my-2 my-sm-0"  %>

  <% end %>

  <%# <form class="form-inline">
    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
    <button class="btn btn-outline-success my-2 my-sm-0 mx-1" type="submit">Search</button>
  </form> %>
</nav>

    <%= yield %>

  </body>
</html>